version: '3.8'

services:
  # Nginx reverse proxy - routes requests to microservices
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front-end
      - books-service
      - warehouse-service
      - orders-service
      - swagger-docs

  # Frontend application
  front-end:
    image: ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main
    volumes:
      - ./adapter:/source/adapter

  # Books microservice (port 3001)
  books-service:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app/services/books-service
    command: npm start
    environment:
      - PORT=3001
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongo:27017/bookstore?authSource=admin
    depends_on:
      - mongo
    expose:
      - "3001"

  # Warehouse microservice (port 3002)
  warehouse-service:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app/services/warehouse-service
    command: npm start
    environment:
      - PORT=3002
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongo:27017/bookstore?authSource=admin
    depends_on:
      - mongo
    expose:
      - "3002"

  # Orders microservice (port 3003)
  orders-service:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app/services/orders-service
    command: npm start
    environment:
      - PORT=3003
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongo:27017/bookstore?authSource=admin
    depends_on:
      - mongo
    expose:
      - "3003"

  # Swagger documentation service (port 3004)
  swagger-docs:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app/services/swagger-docs
    command: npm start
    environment:
      - PORT=3004
      - NODE_ENV=development
    expose:
      - "3004"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

volumes:
  mongodb_data: 