version: '3.8'

services:
  # Nginx reverse proxy - routes requests to microservices
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front-end
      - books-service
      - warehouse-service
      - orders-service
      - swagger-docs

  # Frontend application
  front-end:
    image: ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main
    volumes:
      - ./adapter:/source/adapter

  # Books microservice (port 3001)
  books-service:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app/services/books-service
    command: npm start
    environment:
      - PORT=3001
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongo-books:27017/bookstore?authSource=admin
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
    depends_on:
      - mongo-books
      - rabbitmq
    ports:
      - "3001:3001"

  # Warehouse microservice (port 3002)
  warehouse-service:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app/services/warehouse-service
    command: npm start
    environment:
      - PORT=3002
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongo-warehouse:27017/bookstore?authSource=admin
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
    depends_on:
      - mongo-warehouse
      - rabbitmq
    ports:
      - "3002:3002"

  # Orders microservice (port 3003)
  orders-service:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app/services/orders-service
    command: npm start
    environment:
      - PORT=3003
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongo-orders:27017/bookstore?authSource=admin
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
    depends_on:
      - mongo-orders
      - rabbitmq
    ports:
      - "3003:3003"

  # Swagger documentation service (port 3004)
  swagger-docs:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app/services/swagger-docs
    command: npm start
    environment:
      - PORT=3004
      - NODE_ENV=development
    expose:
      - "3004"

  # Books database (port 27018)
  mongo-books:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_books_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  # Warehouse database (port 27019)
  mongo-warehouse:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongodb_warehouse_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  # Orders database (port 27020)
  mongo-orders:
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - mongodb_orders_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  # RabbitMQ message broker
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    depends_on: []

volumes:
  mongodb_books_data:
  mongodb_warehouse_data:
  mongodb_orders_data:
  rabbitmq_data: 