name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        include:
          - service: front-end
            context: .
            dockerfile: ./Dockerfile
          - service: books-service
            context: .
            dockerfile: ./services/books-service/Dockerfile
          - service: warehouse-service
            context: .
            dockerfile: ./services/warehouse-service/Dockerfile
          - service: orders-service
            context: .
            dockerfile: ./services/orders-service/Dockerfile
          - service: swagger-docs
            context: .
            dockerfile: ./services/swagger-docs/Dockerfile
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push Docker image for main branch
      if: github.event_name == 'push'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}:main
        platforms: linux/amd64
    
    - name: Build and push Docker image for release
      if: github.event_name == 'release'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}:${{ github.event.release.tag_name }}
        platforms: linux/amd64 